disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - notification_center_detachment
  - trailing_whitespace
  - identifier_name
  - valid_ibinspectable
opt_in_rules: # some rules are only opt-in
   - closure_spacing
   - force_unwrapping  
#  # Find all the available rules by running:
#  # swiftlint rules
#included: # paths to include during linting. `--path` is ignored if present.
#  - Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - PhotoGalleryTests

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_unwrapping: error
#force_try:
#  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 
   - 200
   - 300
function_body_length:
  - 65 
  - 90
type_body_length:
  - 300
  - 400
file_length: 
   - 700
   - 800
# they can set both implicitly with an array
#type_body_length:
#  - 300 # warning
#  - 400 # error
# or they can set both explicitly
#file_length:
#  warning: 500
#  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
 min_length: 4 # only warning
 max_length: # warning and error
   warning: 40
   error: 50
 excluded: iPhone # excluded via string
variable_name:
min_length: # only min_length
   warning: 2
   error: 1 # only error
 # excluded: # excluded via string array
 #   - id
 #   - URL
 #   - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit)
