# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoGallery' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'    
  pod 'SwiftLint'
  pod 'Kingfisher', '~> 4.0'
  pod 'Fabric'
  pod 'Crashlytics'

  target 'PhotoGalleryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhotoGalleryUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
